const gulp = require('gulp')
const pug2html = require('./gulp/tasks/pug2html')
const pug_build = require('./gulp/tasks/pug_build')
const style = require('./gulp/tasks/style')
const style_build = require('./gulp/tasks/style_build')
const rename = require('./gulp/tasks/renameIndex')
const copyFonts = require('./gulp/tasks/copyFonts')
const copyIco = require('./gulp/tasks/copyIco')
const copyMailer = require('./gulp/tasks/copyMailer')
const imageMin = require('./gulp/tasks/imageMin')
const server = require('./gulp/tasks/browserSync')
const scp = require('./gulp/tasks/scp')


module.exports.html = gulp.series(pug2html,pug_build,rename)
module.exports.style = gulp.series(style,style_build)
module.exports.run = gulp.series(pug2html,pug_build,rename,style,style_build,copyFonts,copyIco,copyMailer,imageMin)
module.exports.scp = gulp.series(scp)